# https://hub.docker.com/r/ollama/ollama

services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: llm-ollama-container

    volumes:
      - type: volume
        source: ollama
        target: /root/.ollama

    ports:
      - ${OLLAMA_PORT-11434}:11434

    networks:
      - llm_network

    # deploy:
    #   resources:
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       capabilities: [ 'gpu' ]
        #       device_ids: [ '0' ]

    # healthcheck:
    #   test: [ "CMD", "bash", "-c", "nvidia-smi > /dev/null 2>&1" ]
    #   interval: 1m30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 30s

    # pull_policy: always
    # restart: unless-stopped

volumes:
  ollama: {}
