# https://hub.docker.com/_/postgres#-via-docker-compose
# Use postgres/example user/password credentials

services:

  postgres:
    image: postgres
    # restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    
    ports:
      - 5432:5432

    networks:
      - llm_network

  adminer:
    image: adminer
    # restart: always
    ports:
      - 58080:8080
    networks:
      - llm_network