services:
  python:

    # image: python:latest

    build:
      context: .
      dockerfile: python.Dockerfile

    stdin_open: true
    tty: true

    env_file:
      - .env

    volumes:
      - type: bind
        source: .
        target: /home/llm

    ports:
      - ${LLM_API_PORT}:${LLM_API_PORT}

    networks:
      - llm_network

    container_name: llm-python-container
