include:
  - compose.llamacpp.yaml
  - compose.ollama.yaml
  # - compose.vllm.yaml
  - compose.openwebui.yaml
  - compose.mcp.yaml
  - compose.python.yaml
  - compose.postgres.yaml

networks:
  llm_network:
    driver: bridge
