# https://hub.docker.com/r/ollama/ollama

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: llm-ollama
    # pull_policy: always
    tty: true
    # restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

    networks:
      - llm_network

volumes:
  ollama: {}
